apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-vpc-fwr-controller
  namespace: gke-vpc-fwr-controller
  annotations:
    # Replace with your GCP service account email for Workload Identity
    iam.gke.io/gcp-service-account: GCP_SA@HOST_PROJECT.iam.gserviceaccount.com
